name: Build ARM-x86 Image

on:
  push:
    branches:
      - 'master'

jobs:
  # CPU image
  build-base:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Build Base Image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: "./images/base/dockerfile"
          context: "./images/base/"
          platforms: linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pythonlambdalib:trans